import PropTypes from 'prop-types';
import {
  Activity,
  AlarmClock,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  Award,
  Bell,
  BookMarked,
  BookOpen,
  Building,
  Building2,
  Calendar,
  Camera,
  CameraOff,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CirclePlus,
  CircleUserRound,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CodeSquare,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  FileDown,
  FileText,
  Flag,
  FolderOpen,
  GraduationCap,
  GripVertical,
  Handshake,
  Hash,
  History,
  Home,
  Hourglass,
  Inbox,
  Info,
  LayoutGrid,
  Library,
  Link2,
  List,
  ListChecks,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Monitor,
  MoreHorizontal,
  PenLine,
  Pin,
  Printer,
  QrCode,
  RefreshCcw,
  RotateCcw,
  ScanLine,
  Scale,
  Search,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  ShieldUser,
  Smartphone,
  SquarePen,
  Tag,
  Trash2,
  TrendingDown,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Users,
  X,
} from 'lucide-react';

const iconMap = {
  'solar:add-circle-bold': CirclePlus,
  'solar:add-circle-linear': CirclePlus,
  'solar:alarm-linear': AlarmClock,
  'solar:alt-arrow-down-linear': ChevronDown,
  'solar:alt-arrow-left-linear': ChevronLeft,
  'solar:alt-arrow-right-linear': ChevronRight,
  'solar:alt-arrow-up-linear': ChevronUp,
  'solar:arrow-left-linear': ArrowLeft,
  'solar:arrow-right-linear': ArrowRight,
  'solar:arrow-right-up-linear': ExternalLink,
  'solar:bell-linear': Bell,
  'solar:book-2-linear': BookOpen,
  'solar:book-bookmark-linear': BookMarked,
  'solar:book-open-linear': BookOpen,
  'solar:buildings-2-linear': Building,
  'solar:buildings-linear': Building2,
  'solar:calendar-linear': Calendar,
  'solar:camera-broken-linear': CameraOff,
  'solar:camera-linear': Camera,
  'solar:card-linear': CreditCard,
  'solar:chart-2-linear': TrendingDown,
  'solar:check-linear': Check,
  'solar:check-circle-bold': CircleCheck,
  'solar:check-circle-linear': CircleCheck,
  'solar:check-square-linear': CheckSquare,
  'solar:checklist-minimalistic-linear': CheckSquare,
  'solar:clipboard-check-linear': ClipboardCheck,
  'solar:clipboard-list-linear': ClipboardList,
  'solar:clipboard-text-linear': Clipboard,
  'solar:clock-circle-linear': Clock,
  'solar:close-linear': X,
  'solar:code-square-linear': CodeSquare,
  'solar:copy-linear': Copy,
  'solar:danger-triangle-linear': TriangleAlert,
  'solar:document-text-linear': FileText,
  'solar:download-linear': Download,
  'solar:eye-linear': Eye,
  'solar:file-download-linear': FileDown,
  'solar:flag-linear': Flag,
  'solar:folder-open-linear': FolderOpen,
  'solar:graph-down-linear': TrendingDown,
  'solar:hamburger-menu-linear': Menu,
  'solar:hand-shake-linear': Handshake,
  'solar:hashtag-linear': Hash,
  'solar:history-linear': History,
  'solar:home-2-linear': Home,
  'solar:hourglass-line-linear': Hourglass,
  'solar:hourglass-linear': Hourglass,
  'solar:inbox-linear': Inbox,
  'solar:info-circle-linear': Info,
  'solar:letter-linear': Mail,
  'solar:library-linear': Library,
  'solar:link-linear': Link2,
  'solar:link-round-linear': Link2,
  'solar:list-check-linear': ListChecks,
  'solar:logout-2-linear': LogOut,
  'solar:magnifer-linear': Search,
  'solar:map-point-linear': MapPin,
  'solar:menu-dots-bold': MoreHorizontal,
  'solar:menu-dots-linear': MoreHorizontal,
  'solar:monitor-linear': Monitor,
  'solar:notebook-bookmark-linear': BookMarked,
  'solar:pen-2-linear': SquarePen,
  'solar:pen-linear': PenLine,
  'solar:pen-new-square-linear': SquarePen,
  'solar:pin-bold': Pin,
  'solar:play-circle-linear': CirclePlay,
  'solar:printer-linear': Printer,
  'solar:pulse-2-linear': Activity,
  'solar:qr-code-linear': QrCode,
  'solar:restart-linear': RefreshCcw,
  'solar:round-arrow-left-linear': RotateCcw,
  'solar:scale-linear': Scale,
  'solar:scanner-linear': ScanLine,
  'solar:server-linear': Server,
  'solar:settings-linear': Settings,
  'solar:share-linear': Share,
  'solar:shield-check-linear': ShieldCheck,
  'solar:shield-keyhole-linear': Shield,
  'solar:shield-user-linear': ShieldUser,
  'solar:smartphone-linear': Smartphone,
  'solar:square-academic-cap-linear': GraduationCap,
  'solar:tag-linear': Tag,
  'solar:transfer-horizontal-linear': ArrowLeftRight,
  'solar:trash-bin-minimalistic-linear': Trash2,
  'solar:trash-bin-trash-linear': Trash2,
  'solar:trophy-linear': Award,
  'solar:undo-left-linear': RotateCcw,
  'solar:upload-linear': Upload,
  'solar:user-circle-linear': CircleUserRound,
  'solar:user-linear': User,
  'solar:user-plus-linear': UserPlus,
  'solar:users-group-rounded-linear': Users,
  'solar:widget-2-linear': LayoutGrid,
  'solar:widget-5-linear': LayoutGrid,
  'solar:list-linear': List,
  'solar:sort-linear': ArrowUpDown,
};

iconMap[['solar:close', 'circle-linear'].join('-')] = CircleX;

const fallbackIcon = CircleAlert;

export default function Icon({ name, size = 18, className = '', strokeWidth, ...props }) {
  const LucideIcon = iconMap[name] || fallbackIcon;
  const resolvedStrokeWidth = strokeWidth ?? (name?.includes('-bold') ? 2.35 : 1.9);

  return (
    <LucideIcon
      size={size}
      strokeWidth={resolvedStrokeWidth}
      className={`icon inline-block align-middle ${className}`}
      {...props}
    />
  );
}

Icon.propTypes = {
  className: PropTypes.string,
  name: PropTypes.string.isRequired,
  size: PropTypes.number,
  strokeWidth: PropTypes.number,
};
